### ISSUE TITLE
selecting "INBOX" -> response is violating imap protocol

### ISSUE THREAD

**Issue by coldcoff** [mguessan/davmail#122]
Davmail 5.5.1-3299

When explicitely selecting the INBOX the answer is something like

```text
2020-08-25 15:52:35,441 - DEBUG: > BBGH170 SELECT "INBOX"
2020-08-25 15:52:36,971 - DEBUG: < *  1688 EXISTS
```
Please note the TWO spaces between * and 1668.

This is violating the response protocol.
https://tools.ietf.org/html/rfc3501#section-9

![image](https://user-images.githubusercontent.com/14311781/91274300-c2e67480-e77e-11ea-8398-029b3a0c31b2.png)

At least Python imaplib is strict here and throws an exception, as it looks for
```python
r'\* (?P<data>\d+) (?P<type>[A-Z-]+)( (?P<data2>.*))?'
```

It seems that for selecting other folders (other than "INBOX") this issue does not occur.

Can this be fixed, please?

Thank you!

**Comment by mguessan** [comment]
The additional space is related to a workaround to avoid client timeouts with large folders.

You can disable this workaround and thus make DavMail RFC compliant by changing keepalive setting:

`davmail.enableKeepalive=false`

**Comment by duesee** [comment]
Hey @mguessan! I was drawn to this issue because I was about to implement a quirk to accept two spaces in [imap-codec](https://github.com/duesee/imap-codec) to (seemingly) make DavMail work.

Can you explain what exactly is the purpose of the two spaces? Is breaking the response the aim? If so, can't you send garbage or no exists at all?

We were quite confused when we saw this but maybe we miss something.
