### ISSUE TITLE
EWS "ErrorCorruptData Data is corrupt" error

### ISSUE THREAD

**Issue by taylormia** [mguessan/davmail#124]
I'm using DavMail version 5.5.1-3299 with EWS and Thunderbird 68.12.0 on Kubuntu 20.04. Today I started getting the error message below. Any ideas as to how to fix it ? Thanks.

![ksnip_20200908-091634](https://user-images.githubusercontent.com/34145387/92497709-4fe9ee80-f1bf-11ea-8be8-4d72ae932b3f.png)

**Comment by mguessan** [comment]
mismatch between detected Exchange version and event content, would need soap message body to analyse.

**Comment by taylormia** [comment]
Thanks. I'm not getting the error anymore. Most likely an EWS issue.

**Comment by pierre-haessig** [comment]
I'm getting the same error message with "The Organizer property value is not set". 

System: Ubuntu 22.04 with 102.11.0. Davmail freshly updated from 6.0.1 to 6.1.0 (I though it would solve the problem, but it hasn't change much so far). I've configure the Exchange Protocol field as "O365Modern", although I don't know to what extent this is the most suitable choice. Only thing I can say is that I access my professional calendar through the generic address https://outlook.office.com/calendar, not through a customized domain name.

@mguessan you mentioned the need to look at the SOAP message for further analysis, but how to view it? I checked the files ~/davmail.log and didn't see it, nor the error message of the popup by the way.

Also, is it possible to tell Davmail to "drop" certain messages, because for me the error pop up boxes tend to accumulate (I often need to close batches of a dozen of superimposed messages!)
