### ISSUE TITLE
Does not open on Ubuntu 20.04

### ISSUE THREAD

**Issue by raj-magesh** [mguessan/davmail#143]
Davmail doesn't seem to open on Ubuntu 20.04 for me and multiple others using the Ubuntu Software store. When I first installed it, it showed a configuration window, and once I filled it, threw an error message. Every subsequent time I try to open it, it shows the error message without ever opening the configuration window.

The error message is: 
Last message
Unable to bind server socket for SMTP on port 1025: port not allowed or in use by another process
Unable to bind server socket for IMAP on port 1143: port not allowed or in use by another process
Last log
Unable to bind server socket for SMTP on port 1025: port not allowed or in use by another process
Unable to bind server socket for IMAP on port 1143: port not allowed or in use by another process

I've tried removing and reinstalling Davmail but it keeps throwing the same error. Could you please help me troubleshoot? Thanks! :)

**Comment by KingMichaelPark** [comment]
I think that means it's already running

**Comment by mikini** [comment]
Davmail is one of those applications which does its magic invisibly. So normally after configuring it you wouldn't notice it at all unless there is some issue with mail retrieval in you mail client. It is however running under the hood which the "port .. in use by another process" error indicates when you attempt to start another instance. Doing something like `pgrep -fa davmail` will show you the PID of the process and the command line used to start it. 

In its graphical mode, however, Davmail exposes a tray/indicator icon wherever those live on your desktop to indicate it is running and to give the user access to GUI for configuration and log.
In the open world of desktops there are several indicator/systray frameworks to choose from, so it might require some setup on your particular desktop to have this icon show up. Ubuntu uses the GNOME desktop which by default doesn't support the trayicon framework used by Davmail so that is why you do not see any indication of the application running. 
There is an explanation of this issue and suggestions for remedy for several systems/distributions on the homepage under [Davmail Setup->Linux Setup](http://davmail.sourceforge.net/linuxsetup.html).

**Comment by raj-magesh** [comment]
I've recently distro-hopped to Debian running KDE and everything works smoothly. Thanks!
