### ISSUE TITLE
log4j (CVE-2021-44228)

### ISSUE THREAD

**Issue by matisawster** [mguessan/davmail#187]
log4j (CVE-2021-44228)
davmail 6.0.1 use log4j in version 1.2.16 with issue:
Included in Log4j 1.2 is a SocketServer class that is vulnerable to deserialization of untrusted data which can be exploited to remotely execute arbitrary code when combined with a deserialization gadget when listening to untrusted network traffic for log data. This affects Log4j versions up to 1.2 up to 1.2.17.
https://www.cvedetails.com/cve/CVE-2019-17571/

**Comment by hudcap** [comment]
@mguessan I'll take this opportunity to give you a huge, well-deserved thank you for this awesome piece of software!!

Is fixing this as simple as updating the log4j file to the 2.16 version and updating all the pointers to its filename, or will this break things?
I'm a python coder, so I know nothing about Java, but this bug is freaking me out, especially since I run davmail as a public-facing server.

**Comment by holzman** [comment]
@hudcap No, it will take a bit more work than that.  Davmail is using log4j 1.2.16 (which is not affected by the new vulnerability, but hasn't been supported for a long time and has other vulnerabilities like CVE-2019-17571 mentioned above).   We also can't use the bridging libraries since various Appender methods are used - it will need a proper update to the log4j2 API.

**Comment by stefan123t** [comment]
thanks here too for your project.
You may double check CVE-2021-4104 too which should point to the vulnerability of log4j 1.x via JMSAppender configuration.
Though the risk is lower than for CVE-2021-44228 it is comforting to hear you have it on the roadmap.
Happy :christmas_tree:

**Comment by mguessan** [comment]
Thanks @hudcap ,
I do confirm that DavMail is not vulnerable to CVE-2021-44228 as it relies on Log4J 1

My action plan at the moment is:
- upgrade log4j 1 to latest version 1.2.17 (easy)
- avoid potential exposure through vulnerability CVE-2019-17571 by removing impacted classes from released binary

**Comment by hardfalcon** [comment]
Hi, the designated successor to log4j 1.x appears to be [logback](http://logback.qos.ch/), which is actually written (and still maintained) by the same author, and which is supposedly intended to be used as a simple drop-in replacement for log4j 1.x.

Apparently, log4j 2.x was written by different authors, uses a different, incompatible API, and well, has given the world what I'd call the 2021 edition of the vulnerability of the year, due to a fundamentally flawed and misguided API design.

**Comment by stefan123t** [comment]
Dear @mguessan, thanks for your efforts to upgrade to log4j 1.2.17.
Please note that log4j2 has been upgraded to 2.17.0 to mitigate CVE-2021-45105 over the weekend.
That again may support your point that having JNDI and CTX Lookups in the logging framework,
might be contributing to those flaws we have seen over the past days/weeks.
Kind regards,
Stefan

**Comment by mguessan** [comment]
Ok so patch to remove vulnerable Log4J 1 classes (CVE-2019-17571 CVE-2021-4104) from released binaries applied to trunk.
As mentioned above moving to Log4J 2 is probably not a good idea at this point.

The main DavMail dependency is HttpClient, which apparently relies on SLF4J for flexible logging.
=> best approach may be to move to SLF4J for the logging part, then check how to handle the other points:
- interactive logging ui LogFactor: barely used by most users, should probably just remove it
- run time logging configuration through UI and DavMail configuration

**Comment by jpalermo** [comment]
Is there going to be a release cut soon with these changes or should we build from source?

**Comment by mguessan** [comment]
Trunk builds are always available from Appveyor, see https://github.com/mguessan/davmail#trunk-builds

And yes I will probably release an update soon.

**Comment by lcarvalho02** [comment]
@mguessan , I'm trying to download the trunk build from Appveyor but I'm getting an error saying "Artifact not found or access denied.".
