### ISSUE TITLE
Need admin approval

### ISSUE THREAD

**Issue by ytak01** [mguessan/davmail#71]
When the setting of DavMail is set to “O365Manual”, an image like the attachment appears.
DavMail has not been able to get mail.
Is it possible to respond?
![2019-11-13 13_13_20-Sign in to your account](https://user-images.githubusercontent.com/1092622/68732847-41bb5800-0618-11ea-98f9-46a2ae00b18d.png)

**Comment by mguessan** [comment]
This means your Office365 admins do not allow external applications.

You can:
- ask them to approve DavMail (they just need to grant consent on the above screen)
- ask them to register a DavMail application in your Azure Active Directory
- last workaround: use a clientId/redirectUri already approved by your admins, see:
https://sourceforge.net/p/davmail/bugs/702/

**Comment by averter** [comment]
I am experiencing the same problem and need to resort to the "last workaround" but I don't know what I need to do/am confused by all the options available in davmail...
@mguessan my configuration has MFA, I know that with owl I am able to send and receive emails (which suggests OWA?), and results from Microsoft provided test page at: https://testconnectivity.microsoft.com/ indicate that my workplace uses O365. Having stated all this, I am not completely sure of how each of these systems work and what options I need to set. At the moment I have entered this configuration in these lines
````
davmail.oauth.clientId=d3590ed6-52b3-4102-aeff-aad2292ab01c
davmail.oauth.tenantId=
davmail.oauth.redirectUri=urn:ietf:wg:oauth:2.0:oob
````
from the davmail.properties file and am using the O365Interactive protocol, but I am still viewing the same screen as @ytak01 . Thank you in advance for any pointers/help.

**Comment by mguessan** [comment]
With Outlook clientid you should not see the DavMail application admin prompt, please double check you are using the right davmail.properties (or check in settings tab in UI)

**Comment by averter** [comment]
thanks @mguessan. Perhaps it is because I have now entered the clientID and the redirectUri in the UI, I am able to see a white webpage as described in davmail's pop-up window and its url has the form `https://eu-west.azureauth.duosecurity.com/verify?state=mytoken&duo_code=mycode`. 
However, when I paste this URL into the window box nothing happens, the window is simply refreshed and the URL disappears from the box where I have entered it, as shown below.
![image](https://user-images.githubusercontent.com/16647523/193537799-947a6032-de64-4d8c-8f17-f842e67dc0fd.png)
