### ISSUE TITLE
Unable to verify account name or password OSX Catalina

### ISSUE THREAD

**Issue by JensAc** [mguessan/davmail#77]
Hi,
I followed the instructions on http://davmail.sourceforge.net/osxicalsetup.html in order to set up my calendars on OSX Catalina 10.15.1. However, I end up with an "Unable to verify account name or password" error. As a crosscheck I set up the account on an older machine running on OSX Sierra 10.12. On this machine everything works fine.
Do you have any idea what could be going wrong?

**Comment by Romain-Geissler-1A** [comment]
Hi,

I have the same problem. Checking the logs, indeed OSX doesn't send any Authorization header. Checking this problem elsewhere, it seems it affected/affects many people, and the reason is Apple decided to stop sending credentials altogether is SSL is disabled. I haven't tried yet, but I would expect that setting up SSL on DavMail side, accepting the SSL certificate on OS side (people advice to use Safari to browse https://localhost:1080 for that), and then toggling "SSL" when setting up the DavCal account should work.

Cheers,
Romain

**Comment by JensAc** [comment]
Hi, 
you are totally right, I also tested setting up SSL on the DavMail side and was able to connect successfully but I did not update this issue. Thanks for pointing out the correct solution. I will close this for now.
